<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font awesome -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('/assets/fontawesome-5.9.0/css/all.min.css'); ?>">

    <link rel="stylesheet" href="<?php echo $this->baseUrl("/assets/css/main.css"); ?>">

    <title>Thizer Soundboard</title>



  </head>
  <body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS  -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <div class="container pt-3">
      <div class="row">
        <div class="col-12 col-md-6">
          <h1><i class="fas fa-podcast"></i> Thizer Soundboard</h1>
        </div>
        <div class="col-12 col-md-6 text-right">
          <a class="btn btn-warning mt-3 d-none d-md-inline-block" href="https://github.com/thizer/soundboard" target="_blank">
            <i class="fab fa-github-alt"></i>
            View on Github
          </a>

          <a class="btn btn-warning m-3 float-left d-inline-block d-md-none" href="https://github.com/thizer/soundboard" target="_blank">
            <i class="fab fa-github-alt"></i>
            View on Github
          </a>
        </div>
        <div class="col-12">
          <h4>
            Click the button below and play it's sound and have fun!
          </h4>
        </div>
      </div>
      <hr/>
      <?php echo $content; ?>

<!--      <span class="mt-5 text-warning" style="">
        <form action="<?php echo $this->baseUrl("/index/new-sound"); ?>" method="post" enctype="multipart/form-data">
          <input type="hidden" name="fileToUpload" id="fileToUpload">
          <button type="" class="btn btn-outline-warning">Updload</button> New sound file
        </form>
      </span>-->
    </div>

  </body>
</html>



