<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/js/play-button.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/assets/js/player-control.js'); ?>"></script>

<?php
  $i=0;
  $indexColor = 0;
  $colors = [
    'btn-outline-primary rounded rounded-circle',
    'btn-outline-secondary rounded-circle',
    'btn-outline-success rounded-circle',
    'btn-outline-danger rounded-circle',
    'btn-outline-info rounded-circle',
    'btn-outline-dark rounded-circle'
  ];
?>
<div class="row">
  <div class="col-12 col-sm-5">
    <h2>Favorites</h2>
  </div>
  <div class="col-12 col-sm-7 text-right">

    <div class="input-group">
  <div class="custom-file">
    <input type="file" accept= "audio/*" class="custom-file-input" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04">
    <label class="custom-file-label" for="inputGroupFile04"></label>
  </div>
  <div class="input-group-append">
    <button class="btn btn-outline-warning" type="button" id="inputGroupFileAddon04">Upload Your Audio FIle</button>
  </div>
</div>


  </div>
</div>
<div class="d-flex justify-content-between flex-wrap" id="favorites">
  <?php for ($i; $i<90; $i++): ?>
    <div class="border rounded fav-item" id="fav-<?php echo $i; ?>" ondragover="console.log(event.target);"></div>
  <?php endfor; ?>
</div>
<hr/>
<div class="d-flex justify-content-between flex-wrap">
  <?php foreach ($sounds as $theme => $files): ?>
    <?php if ($indexColor >= count($colors)) $indexColor=0; ?>
    <?php foreach($files as $filename): $i++; ?>

      <button type="button" class="m-2 btn btn-sound <?php echo $colors[$indexColor]; ?>" id="btn-<?php echo $i; ?>" onclick="playSound('<?php echo $i; ?>');" data-state="stoped" data-toggle="tooltip" title="<?php echo preg_replace(array('/.+\//', '/\-/'), array('', ' '), $filename); ?>" draggable="true">
        <?php //echo preg_replace(array('/.+\//', '/\-/'), array('', ' '), $filename); ?>
        <i class="fas fa-eject fa-rotate-90"></i>
      </button>

      <audio src="<?php echo $this->baseUrl($soundsPath.$filename); ?>" id="item-<?php echo $i; ?>">
          Your browser does not support the HTML5 Audio element.
      </audio>

    <?php endforeach; ?>
  <?php $indexColor++; endforeach; ?>
</div>

